# Kafka IO
KAFKA_HOST: localhost
KAFKA_CLIENT_PORT: 9092
KAFKA_TOPICS: [electrical,hvac,motion,thermo,totalenergy,totalwater,water]
KAFKA_PARTITIONS: 1

# Zookeeper
# ZK_HOST: localhost
# ZK_PORT: 8081

logger_name: iot_sensors_logger

# simulation parameters
base_interval_mins: 30
msgs_per_sec: 4

